@extends('layouts.app')
@section('title','Detalle de granja')
@section('content')
@php $cap=$farm->panels->sum(fn($p)=>$p->nominal_power_kw*$p->pivot->quantity); $total=$history->sum('real_kwh'); @endphp
@if($farm->photo_path)
<style>html body .farm-detail-hero>img:first-child{display:none}html body .farm-detail-hero>.farm-real-photo{display:block;width:100%;height:230px;object-fit:cover}@media(max-width:760px){html body .farm-detail-hero>.farm-real-photo{height:180px}}</style>
<script>document.addEventListener('DOMContentLoaded',()=>{const hero=document.querySelector('.farm-detail-hero');const fallback=hero?.querySelector('img');if(hero&&fallback){const photo=document.createElement('img');photo.className='farm-real-photo';photo.src={{ Js::from(asset('storage/'.$farm->photo_path)) }};photo.alt={{ Js::from('Fotografía de '.$farm->name) }};hero.insertBefore(photo,fallback.nextSibling);}});</script>
@endif
<style>
html body .farm-detail-hero{overflow:hidden;margin-bottom:24px;border:1px solid #45577e;border-radius:20px;background:#111d38}
html body .farm-detail-hero>img{display:block;width:100%;height:230px;object-fit:cover}
html body .farm-detail-hero .page-heading{padding:24px;margin:0}
html[data-theme="dark"] body .farm-detail-hero .page-heading{position:relative;inset:auto}
html[data-theme="dark"] body .farm-detail-hero::after{display:none}
html body .farm-detail-hero .page-heading p{color:#dbe5ff!important}
@media(max-width:760px){html body .farm-detail-hero>img{height:180px}html body .farm-detail-hero h1{font-size:2rem;overflow-wrap:anywhere}}
</style>
<div class="farm-detail-hero"><img src="{{ asset('images/farms/farm-'.(($farm->id - 1) % 7 + 1).'.png') }}" alt="Imagen de {{ $farm->name }}"><div class="page-heading"><div><a class="back-link" href="{{ route('farms.index') }}">← Volver a granjas</a><h1>{{ $farm->name }}<span class="heading-dot">.</span></h1><p><x-icon name="pin"/> {{ $farm->location_name }} · {{ $farm->department->name }} <span class="pill {{ $farm->is_active?'positive':'neutral' }}">{{ $farm->is_active?'Activa':'Inactiva' }}</span></p></div>@auth<a class="button button-white" href="{{ route('farms.edit',$farm) }}"><x-icon name="edit"/> Editar granja</a>@endauth</div></div>
<div class="summary-strip"><div><span>Capacidad instalada</span><strong>{{ number_format($cap,2) }} <small>kW</small></strong></div><div><span>Paneles instalados</span><strong>{{ number_format($farm->panels->sum('pivot.quantity')) }}</strong></div><div><span>Familias beneficiadas</span><strong>{{ number_format($farm->families_count) }}</strong></div><div><span>CO₂ evitado histórico</span><strong>{{ number_format($total*.4/1000,2) }} <small>t</small></strong></div></div>
<div class="detail-grid"><section class="card"><div class="card-heading"><div><h2>Generación histórica</h2><p>Registro mensual de energía real y esperada.</p></div>@auth<a class="text-link" href="{{ route('generations.create',['solar_farm_id'=>$farm->id]) }}"><x-icon name="plus"/> Registrar</a>@endauth</div><div class="table-scroll"><table><thead><tr><th>Período</th><th class="number">Real · kWh</th><th class="number">Esperada · kWh</th><th class="number">Desempeño</th></tr></thead><tbody>@forelse($history->sortByDesc('period') as $r)<tr><td>{{ $r->period->format('m/Y') }}</td><td class="number">{{ number_format($r->real_kwh,2) }}</td><td class="number">{{ number_format($r->expected_kwh,2) }}</td><td class="number">@if($r->expected_kwh>0)<span class="pill {{ $r->real_kwh<=$r->expected_kwh*.8?'warning':'positive' }}">{{ number_format($r->real_kwh/$r->expected_kwh*100,1) }}%</span>@else<span class="muted">Sin base</span>@endif</td></tr>@empty<tr><td colspan="4" class="empty-inline">Esta granja aún no tiene generación registrada.</td></tr>@endforelse</tbody></table></div></section><div class="detail-side"><section class="card form-card"><h2>Datos de la instalación</h2><dl class="detail-list"><div><dt>Departamento</dt><dd>{{ $farm->department->name }}</dd></div><div><dt>Coordenadas</dt><dd>{{ $farm->latitude }}, {{ $farm->longitude }}</dd></div><div><dt>En operación desde</dt><dd>{{ $farm->commissioned_at?->format('d/m/Y')??'No registrada' }}</dd></div></dl><a class="text-link" href="{{ route('map',['solar_farm_id'=>$farm->id]) }}">Ubicar en el mapa <x-icon name="arrow"/></a>@if($farm->notes)<p class="note-text">{{ $farm->notes }}</p>@endif</section><section class="card form-card"><h2>Composición de paneles</h2>@forelse($farm->panels as $p)<div class="panel-detail"><span class="metric-icon amber"><x-icon name="farm"/></span><div><strong>{{ $p->brand }} {{ $p->model }}</strong><small>{{ number_format($p->pivot->quantity) }} × {{ $p->nominal_power_kw }} kW</small></div></div>@empty<p class="muted">No hay paneles asociados.</p>@endforelse</section><a class="projection-cta" href="{{ route('projections.index',['solar_farm_id'=>$farm->id]) }}"><x-icon name="trend"/><strong>Explora su próxima generación</strong><span>Ver proyecciones <x-icon name="arrow"/></span></a>@auth @if($farm->is_active)<form method="POST" action="{{ route('farms.destroy',$farm) }}" data-confirm="¿Desactivar esta granja? Se conservarán sus datos históricos.">@csrf @method('DELETE')<button class="button button-danger full-width">Desactivar granja</button></form>@endif @endauth</div></div>
@include('farms.history-chart')
@endsection
