@extends('layouts.app')
@section('title', 'Panorama nacional')
@section('content')
@php $t = $dashboard['totals']; $nf = fn($v,$d=0) => number_format($v ?? 0,$d,'.',','); @endphp
<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-line"></span> EL PODER DEL SOL, EN DATOS</div><h1>Panorama nacional<span class="heading-dot">.</span></h1><p>Así avanza la energía solar en Guatemala. Explora su impacto.</p></div><a class="button button-white" href="{{ route('reports.export', request()->query()) }}"><x-icon name="download"/> Exportar reporte</a></div>
@include('partials.filters')
<section class="metrics-grid" aria-label="Indicadores principales">
    <article class="metric-card metric-energy"><div class="metric-top"><span>Generación acumulada</span><span class="metric-icon"><x-icon name="bolt"/></span></div><div class="metric-value">{{ $nf($t['generation_kwh']) }} <small>kWh</small></div><div class="metric-meta"><span class="pill dark-green">{{ $nf($t['performance'],1) }}% de lo esperado</span><span>Período seleccionado</span></div><div class="energy-decoration" aria-hidden="true">ϟ</div></article>
    <article class="metric-card"><div class="metric-top"><span>Capacidad instalada</span><span class="metric-icon amber"><x-icon name="sun"/></span></div><div class="metric-value">{{ $nf($t['capacity_kw'],1) }} <small>kW</small></div><div class="metric-meta"><span class="mini-dot amber-bg"></span> {{ $nf($t['panels']) }} paneles <span class="muted">· Inventario actual</span></div></article>
    <article class="metric-card"><div class="metric-top"><span>Familias beneficiadas</span><span class="metric-icon blue"><x-icon name="users"/></span></div><div class="metric-value">{{ $nf($t['families']) }}</div><div class="metric-meta"><x-icon name="farm"/> {{ $nf($t['farms']) }} granjas <span class="muted">· {{ $nf($t['active_farms']) }} activas</span></div></article>
    <article class="metric-card"><div class="metric-top"><span>CO₂ evitado</span><span class="metric-icon mint"><x-icon name="leaf"/></span></div><div class="metric-value">{{ $nf($t['co2_tonnes'],1) }} <small>t</small></div><div class="metric-meta"><span class="mini-dot green"></span> {{ $nf($t['co2_kg']) }} kg <span class="muted">· Impacto estimado</span></div></article>
</section>
<div class="dashboard-main-grid">@include('partials.trend') @include('partials.map')</div>
<div class="dashboard-bottom-grid">
    <section class="card ranking-card"><div class="card-heading"><div><span class="eyebrow">LIDERANDO EL CAMBIO</span><h2>Generación por departamento</h2></div><a class="text-link" href="{{ route('reports', request()->query()) }}">Ver reporte <x-icon name="arrow"/></a></div><div class="ranking-list">@php $top = collect($dashboard['ranking'])->sortByDesc('generation_kwh')->take(5); $max = max(1,$top->max('generation_kwh') ?? 1); @endphp @forelse($top as $item)<a class="ranking-row" href="{{ route('reports', ['department_id'=>$item['id']]) }}"><span class="rank-number">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><div class="rank-detail"><div class="rank-name"><strong>{{ $item['name'] }}</strong><span>{{ $nf($item['generation_kwh']) }} <small>kWh</small></span></div><div class="rank-track"><span style="width:{{ max(1,($item['generation_kwh']/$max)*100) }}%;background:{{ $loop->first ? '#1e8968' : '#a4c8b8' }}"></span></div></div></a>@empty<div class="empty-inline">No hay resultados en el período seleccionado.</div>@endforelse</div></section>
    <section class="card alert-card"><div class="card-heading"><div><span class="eyebrow">ATENCIÓN A TIEMPO</span><h2>Alertas de generación <span class="count-badge">{{ $t['alerts'] }}</span></h2></div><x-icon name="alert" class="icon amber-text"/></div><p class="card-description">Granjas con generación 20% o más por debajo de lo esperado.</p><div class="alerts-preview">@forelse(collect($dashboard['alerts'])->take(3) as $alert)@php $record=$alert->generationRecord; @endphp<a class="alert-preview-row" href="{{ route('farms.show',$record->solarFarm) }}"><span class="alert-circle"><x-icon name="bolt"/></span><div><strong>{{ $record->solarFarm->name }}</strong><small>{{ $record->solarFarm->department->name }} · {{ $record->period->format('m/Y') }}</small></div><span class="pill warning">−{{ $nf($alert->deviation_percent,1) }}%</span></a>@empty<div class="all-good"><span><x-icon name="check"/></span><strong>La energía va por buen camino</strong><p>No hay alertas para los filtros seleccionados.</p></div>@endforelse</div><a class="alert-footer" href="{{ route('alerts.index',request()->query()) }}">Revisar todas las alertas <x-icon name="arrow"/></a></section>
</div>
<div class="environment-strip"><span class="environment-icon"><x-icon name="leaf"/></span><div><strong>Medimos energía. Visualizamos el cambio.</strong><p>Cada kWh de energía solar representa 0.40 kg de CO₂ evitado.</p></div><span class="environment-tag">UN PAÍS · 22 DEPARTAMENTOS</span></div>
@endsection
