@extends('layouts.app')
@section('title','Reportes por departamento')
@section('content')
@php $t=$dashboard['totals']; $nf=fn($v,$d=0)=>number_format($v??0,$d,'.',','); @endphp
<div class="page-heading"><div><div class="eyebrow"><span class="eyebrow-line"></span> DEL DATO A LA DECISIÓN</div><h1>El impacto, en perspectiva<span class="heading-dot">.</span></h1><p>Compara los resultados de cada departamento y descarga sus indicadores.</p></div><a class="button button-dark" href="{{ route('reports.export',request()->query()) }}"><x-icon name="download"/> Descargar CSV</a></div>
@include('partials.filters')
<section class="card"><div class="card-heading"><div><h2>Recibe este reporte por correo</h2><p>Te enviaremos el CSV con los filtros actuales. Puedes usar Gmail u otro correo.</p></div></div>
<form method="POST" action="{{ route('reports.email') }}" class="report-email-form" data-submit-form>@csrf
@foreach($filters as $key => $value)<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endforeach
<label class="field" for="report-email">Correo destinatario<input type="email" id="report-email" name="email" autocomplete="email" maxlength="254" placeholder="nombre@gmail.com" required></label>
<button class="button button-dark" type="submit">Enviar CSV por correo</button>
</form></section>
<div class="summary-strip"><div><span>Generación real</span><strong>{{ $nf($t['generation_kwh']) }} <small>kWh</small></strong></div><div><span>Generación esperada</span><strong>{{ $nf($t['expected_kwh']) }} <small>kWh</small></strong></div><div><span>Cumplimiento</span><strong>{{ $nf($t['performance'],1) }}<small>%</small></strong></div><div><span>CO₂ evitado</span><strong>{{ $nf($t['co2_tonnes'],2) }} <small>toneladas</small></strong></div></div>
<section class="card"><div class="card-heading"><div><h2>Comparativo departamental</h2><p>Generación y CO₂ del período; activos y beneficiarios del inventario actual.</p></div><span class="pill neutral">{{ count($dashboard['ranking']) }} departamentos</span></div><div class="table-scroll"><table><thead><tr><th>Departamento</th><th class="number">Granjas</th><th class="number">Paneles</th><th class="number">Capacidad<br><small>kW</small></th><th class="number">Real<br><small>kWh</small></th><th class="number">Esperada<br><small>kWh</small></th><th class="number">Familias</th><th class="number">CO₂<br><small>kg / t</small></th><th class="number">Cumplimiento</th></tr></thead><tbody>@forelse($dashboard['ranking'] as $item)<tr><td><a class="table-name" href="{{ route('farms.index',['department_id'=>$item['id']]) }}"><i class="legend-dot" style="background:{{ $item['color'] }}"></i>{{ $item['name'] }}</a></td>@foreach(['farms','panels','capacity_kw','generation_kwh','expected_kwh','families'] as $key)<td class="number">{{ $nf($item[$key],$key==='capacity_kw'?1:0) }}</td>@endforeach<td class="number">{{ $nf($item['co2_kg']) }}<small class="block muted">{{ $nf($item['co2_tonnes'],2) }} t</small></td><td class="number">@if($item['expected_kwh']>0)<span class="pill {{ $item['performance']<=80?'warning':'positive' }}">{{ $nf($item['performance'],1) }}%</span>@else<span class="muted">Sin base</span>@endif</td></tr>@empty<tr><td colspan="9" class="empty-inline">No hay departamentos para estos filtros.</td></tr>@endforelse</tbody><tfoot><tr><th>Total</th>@foreach(['farms','panels','capacity_kw','generation_kwh','expected_kwh','families'] as $key)<td class="number">{{ $nf($t[$key],$key==='capacity_kw'?1:0) }}</td>@endforeach<td class="number">{{ $nf($t['co2_kg']) }}<small class="block">{{ $nf($t['co2_tonnes'],2) }} t</small></td><td class="number">{{ $nf($t['performance'],1) }}%</td></tr></tfoot></table></div></section>
<div class="report-chart">@include('partials.trend')</div>
@endsection
